# .github/workflows/deploy.yml
name: Deploy Quartz Site

on:
  push:
    branches: ["main"] # Or your main branch name, e.g., "master"
    paths:
      - "content/**"
      - "quartz.config.ts"
      - "quartz.layout.ts"
      - "quartz/**"
      - ".github/workflows/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for Quartz Graph

      - uses: actions/setup-node@v4
        with:
          node-version: "22" # Ensure this matches your local nvm version

      - name: Install dependencies
        run: npm ci # Use npm ci for clean installs in CI environments

      - name: Build Quartz
        run: npx quartz build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # Use v4 for Node 20+ compatibility
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # Quartz builds to the 'public' directory
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          # cname: example.com # Uncomment and set if you have a custom domain